version: '4.0'
services:
  docker:
    image: docker:dind
    container_name: docker
    restart: always
    privileged: true
    networks:
      - docker-daemon
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ../cert:/certs/server
    ports:
      - "2376:2376"
      - "8081:8081"

  jenkins:
    image: myjenkins-blueocean:0.1
    container_name: jenkins
    restart: on-failure
    networks:
      - docker-daemon
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client # Update path to client certificate
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ../cert:/certs/client:ro # Update volume path
      - ../jinkens_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - docker

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../ngrok_home/ngrok.yml:/etc/ngrok.yml
      - ../ngrok_home/log/ngrok.log:/var/log/ngrok.log
    ports:
      - 4040:4040
    depends_on:
      - docker
      - jenkins

networks:
  docker-daemon:
    driver: bridge

